---
title: "20221007-Melanogaster-lines-Prettgeri"
output: github_document
date: '2022-11-11'
---

```{r}
library("survival")
library("survminer")
```

### Loop to convert the example data.frame 'df' into properly formatted data.frame 'results'
```{r}
#write a function to transform a data.frame that has the column format 'vial | treatment | D0 | D1 | D2...', with one row for each vial
#into a long version in tidy format that can be input to make a survivorship curve
convert_df<-function(df){
  #open empty data.frame to store results
  results<-data.frame(vial=character(),treatment=character(),dead=numeric(),status=numeric())
  #This loop will index out each row (one row per vial) one at a time, transform it into long format (one row per fly), and add the information to the empty data.frame called results
  for(i in 1:nrow(df)){
  #isolate the row (vial) you want to work on
  temp<-df[i,]
    #iteratively isolate each day for this vial (day 0 must be column 3, day 1 column 4, etc.). Loop stops the column before the last day
    for(j in 3:(ncol(temp)-1)){
      #assign the number of flies that died in the vial on that day (starting with day 1) to the variable 'z'
      z<-temp[1,j]-temp[1,j+1]
        #if >0 flies died add this information to the results dataframe
        if(z>0){
          #iterate over 1 through total number of dead flies
          for(k in 1:z){
            #add a new row to the 'results' data.frame for the given dead fly, specifying vial #, treatment, day died, and
            #record the current vial #
            vial<-temp[,1]
            #record the genotype of the current vial
            treatment<-temp[,2]
            #record the death date of the flies that died on this day (assumes that your input DF starts with day 0 in column 3)
            dd<-j-2
            #append this information into a new row in the 'results' data.frame, and add a '1' in the 4th column to indicate mortality
            results[nrow(results)+1,]<- c(vial,treatment,dd,1)
          } #close for loop
        } #close if loop
    } #close for loop
  
  #now assign the number of flies remaining in the vial on the last day (value in the last column of the row) to the variable 'z'
  z<-temp[1,j+1]
    #if there are any flies alive in the vial on the last day
    if(z>0){
      #iterate over 1:(number of flies alive on the last day)
      for(l in 1:z){
        #record the current vial #
        vial<-temp[,1]
        #record the genotype of the current vial
        treatment<-temp[,2]
        #record the last day we recorded this fly alive (assumes that your input DF starts with day 0 in column 3)
        dd<-j-2
        #append this information into a new row in the 'results' data.frame, and add a '0' in the 4th column to indicate that the fly made it to the end of the experiment
        results[nrow(results)+1,]<- c(vial,treatment,dd,0)
      } #close for loop
    } #close if loop
  } #close original for loop
results$dead<-as.numeric(results$dead)  #reiterate that this column must be class numeric
results$status<-as.numeric(results$status)  #reiterate that this column must be class numeric
results$vial <- as.factor(results$vial) # make sure vial is considered a factor
# gives you only the results dataframe as output from function 
return(results) 
} #close function


```



### Read in the real raw data and make subsets
```{r}
# read the file from csv
melanogaster_lines <-read.csv("~/Desktop/Github/Unckless_Lab_Resources/Infection_survival_analyses/20221007/20221007_Prettgeri_infections .csv")

```

### Subset to different Lines and only the columns needed too at the same time

```{r}

# W1118
W1118_subset <- melanogaster_lines[c(1,4:5,12),c(1,3,10:17)]

# C564
C564_subset <- melanogaster_lines[c(6,10:11),c(1,3,10:17)]

# IMD null 
IMD_subset <- melanogaster_lines[c(3,8,13),c(1,3,10:17)]

# dpt null 
dpt_subset <- melanogaster_lines[c(2,7,9),c(1,3,10:17)]

```

### Covert each dataframe to the format needed to make the plots 
```{r}
# W118
W1118_sub_convert<-convert_df(W1118_subset)

# C564
C564_sub_convert<-convert_df(C564_subset)

# IMD null 
IMD_sub_convert<-convert_df(IMD_subset)

# dpt null
dpt_sub_convert<-convert_df(dpt_subset)

```

### W1118 plot
```{r}
W1118_sub_convert_fit<- survfit(Surv(dead, status) ~ treatment, data=W1118_sub_convert)
ggsurvplot(W1118_sub_convert_fit,
          pval = TRUE, conf.int = TRUE,
          #risk.table = TRUE, # Add risk table
          #risk.table.col = "strata", # Change risk table color by groups
          linetype = "strata", # Change line type by groups
          # surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw()) # Change ggplot2 theme
```
### C564 plot
```{r}
C564_sub_convert_fit<- survfit(Surv(dead, status) ~ treatment, data=C564_sub_convert)
ggsurvplot(C564_sub_convert_fit,
          pval = TRUE, conf.int = TRUE,
          #risk.table = TRUE, # Add risk table
          #risk.table.col = "strata", # Change risk table color by groups
          linetype = "strata", # Change line type by groups
          # surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw()) # Change ggplot2 theme
```
### IMD null plot
```{r}
IMD_sub_convert_fit<- survfit(Surv(dead, status) ~ treatment, data=IMD_sub_convert)
ggsurvplot(IMD_sub_convert_fit,
          pval = TRUE, conf.int = TRUE,
          #risk.table = TRUE, # Add risk table
          #risk.table.col = "strata", # Change risk table color by groups
          linetype = "strata", # Change line type by groups
          # surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw()) # Change ggplot2 theme
```

### Dpt null plot
```{r}
dpt_sub_convert_fit<- survfit(Surv(dead, status) ~ treatment, data=dpt_sub_convert)
ggsurvplot(dpt_sub_convert_fit,
          pval = TRUE, conf.int = TRUE,
          #risk.table = TRUE, # Add risk table
          #risk.table.col = "strata", # Change risk table color by groups
          linetype = "strata", # Change line type by groups
          # surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw()) # Change ggplot2 theme
```