---
title: "Fluid-concentration-analysis"
format: gfm
editor: visual
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(Rmisc)
library(rstatix)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi=300,fig.fig.width=7, fig.height = 4.5)
```

Load in dataset

```{r}
DNA <- read.csv("/Users/maggieschedl/Desktop/Github/Unckless_Lab_Resources/qPCR_analysis/fluid_concentration/fluid_concentration.csv")
```

Plot total DNA yield

```{r}

# make order of type of sample treatment 
DNA$type <- factor(DNA$type, levels=c("raw supernatant", "Sartorius centrifuged", "millipore small centrifuged"))

# get statistics on this for standard error bars 
stats <- summarySE(DNA, measurevar="total.DNA", groupvars=c("type"))
stats


# plot 
ggplot(DNA, aes(y=total.DNA, x=type, fill=type)) + 
  geom_errorbar(aes(ymin = total.DNA-se, ymax = total.DNA+se, color = type),data = stats, position = position_dodge(0.3), width = 0.2)+
  geom_point(aes(color = type), position = position_dodge(0.3), size = 4.5) +
  scale_color_manual(values = c("#55d0ff","#77aaff", "#2C67F2")) + theme_light() + 
  theme(axis.text=element_text(size=14),axis.title=element_text(size=16), title =element_text(size =16)) + labs(title = "Comparing Yield of DNA from Concentrated \nCell Cuture Supernatant",y = "Total DNA (ng)", x = "Sample Treatment")  + theme(legend.position = "none") + scale_y_continuous(
    trans = pseudo_log_trans(base = 10), breaks = c(0,10, 50, 100)) + scale_x_discrete(labels=c("raw supernatant" = "Unconcentrated \nSupernatant", "Sartorius centrifuged" = "Sartorius \nCentrifuged", "millipore small centrifuged" = "Sartorius and \nMillipore \nCentrifuged"))
```

T test

```{r}
stat.test <- DNA %>%
  t_test(total.DNA ~ type) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")
stat.test
```

what is the mean for each type?

```{r}
# separate supernatant only
sup <- DNA[which(DNA$type == "raw supernatant"),]
supmean <- mean(sup$total.DNA)
supmean
# separate sartorius centrifuged
sart <- DNA[which(DNA$type == "Sartorius centrifuged"),]
smean <- mean(sart$total.DNA)
smean

# separate sartorius and millipore
mill <- DNA[which(DNA$type == "millipore small centrifuged"),]
milmean <- mean(mill$total.DNA)
milmean
```

Anova for testing differences (better than pairwise t tests)

```{r}
# anova looking at relationship between DNA yield and sample type
anov_concentration <- aov(total.DNA ~ type, data = DNA)
summary(anov_concentration)

# post-hoc tukey test to show what the differences are 
tukey_concentration <-TukeyHSD(anov_concentration)
tukey_concentration
```
